version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5444:5432"
    env_file: .env
    restart: unless-stopped
    networks:
      - server-net

volumes:
  postgres:

networks:
  server-net:
    name: server-net
    driver: bridge
