version: "3.8"

services:
  redis:
    env_file: .env.development
    container_name: redis
    image: redis:latest
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM}'
      - '--maxmemory-policy ${REDIS_POLICY}'
      - '--requirepass ${REDIS_PASS}'
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped

  backend:
    env_file: .env.development
    build: .
    container_name: backend
    ports:
      - "8181:8181"
      - "3232:3232"
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  wireguard:
