import { MigrationInterface, QueryRunner } from "typeorm";

export class Messenger1790355565150 implements MigrationInterface {
    name = 'Messenger1790355565150'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."contacts_status_enum" AS ENUM('pending', 'accepted', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "contact_user_id" uuid NOT NULL, "display_name" character varying(80), "status" "public"."contacts_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CONTACTS_CONTACT_USER" ON "contacts"  ("contact_user_id", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CONTACTS_USER_CONTACT" ON "contacts"  ("user_id", "contact_user_id") `);
        await queryRunner.query(`CREATE TABLE "message_attachments" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "message_id" uuid NOT NULL, "file_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e5085d973567c61e9306f10f95b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_MSG_ATTACHMENTS_MESSAGE" ON "message_attachments"  ("message_id") `);
        await queryRunner.query(`CREATE TABLE "message_deletions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_78cd6a9f486b4a2942265e25f90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_MESSAGE_DELETIONS_USER_MESSAGE" ON "message_deletions"  ("message_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGE_DELETIONS_MESSAGE" ON "message_deletions"  ("message_id") `);
        await queryRunner.query(`CREATE TABLE "message_mentions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "message_id" uuid NOT NULL, "user_id" uuid, "is_all" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6d3047d9fb0dd841366be90fb87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_MENTIONS_USER" ON "message_mentions"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_MENTIONS_MESSAGE" ON "message_mentions"  ("message_id") `);
        await queryRunner.query(`CREATE TABLE "message_reactions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "emoji" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_654a9f0059ff93a8f156be66a5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_REACTIONS_MESSAGE_USER" ON "message_reactions"  ("message_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_REACTIONS_MESSAGE" ON "message_reactions"  ("message_id") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'image', 'file', 'voice', 'system', 'poll')`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum" AS ENUM('sent', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "chat_id" uuid NOT NULL, "sender_id" uuid, "type" "public"."messages_type_enum" NOT NULL DEFAULT 'text', "content" text, "reply_to_id" uuid, "forwarded_from_id" uuid, "status" "public"."messages_status_enum" NOT NULL DEFAULT 'sent', "is_edited" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_pinned" boolean NOT NULL DEFAULT false, "pinned_at" TIMESTAMP WITH TIME ZONE, "pinned_by_id" uuid, "keyboard" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_SENDER" ON "messages"  ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_CHAT_CREATED_ID" ON "messages"  ("chat_id", "created_at", "id") `);
        await queryRunner.query(`CREATE TABLE "chat_folders" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "name" character varying(50) NOT NULL, "position" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_14443ca041335fec84cb7a43333" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CHAT_FOLDERS_USER_NAME" ON "chat_folders"  ("user_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_CHAT_FOLDERS_USER" ON "chat_folders"  ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_members_role_enum" AS ENUM('owner', 'admin', 'member', 'subscriber')`);
        await queryRunner.query(`CREATE TABLE "chat_members" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "chat_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."chat_members_role_enum" NOT NULL DEFAULT 'member', "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "muted_until" TIMESTAMP WITH TIME ZONE, "last_read_message_id" uuid, "unread_count" integer NOT NULL DEFAULT '0', "is_pinned_chat" boolean NOT NULL DEFAULT false, "pinned_chat_at" TIMESTAMP WITH TIME ZONE, "folder_id" uuid, "hidden_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_aea646f59c92c47af5804ce73a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CHAT_MEMBERS_USER" ON "chat_members"  ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CHAT_MEMBERS_CHAT_USER" ON "chat_members"  ("chat_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chats_type_enum" AS ENUM('direct', 'group', 'channel')`);
        await queryRunner.query(`CREATE TYPE "public"."chats_last_message_type_enum" AS ENUM('text', 'image', 'file', 'voice', 'system', 'poll')`);
        await queryRunner.query(`CREATE TABLE "chats" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "type" "public"."chats_type_enum" NOT NULL DEFAULT 'direct', "direct_key" character varying(73), "name" character varying(100), "avatar_id" uuid, "created_by_id" uuid, "description" character varying(500), "username" character varying(50), "is_public" boolean NOT NULL DEFAULT false, "slow_mode_seconds" integer NOT NULL DEFAULT '0', "last_message_at" TIMESTAMP WITH TIME ZONE, "last_message_id" uuid, "last_message_content" character varying(200), "last_message_type" "public"."chats_last_message_type_enum", "last_message_sender_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_cc53aae48c75092f437988a8834" UNIQUE ("username"), CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CHATS_DIRECT_KEY" ON "chats"  ("direct_key") WHERE direct_key IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CHATS_USERNAME" ON "chats"  ("username") WHERE username IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_CHATS_LAST_MESSAGE_AT" ON "chats"  ("last_message_at") `);
        await queryRunner.query(`CREATE TABLE "chat_bans" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "chat_id" uuid NOT NULL, "user_id" uuid NOT NULL, "banned_by" uuid, "reason" character varying(500), "until" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6ce17fb5dbf64f9363c69fc1b45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CHAT_BANS_USER" ON "chat_bans"  ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CHAT_BANS_CHAT_USER" ON "chat_bans"  ("chat_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "chat_invites" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "chat_id" uuid NOT NULL, "code" character varying(32) NOT NULL, "created_by_id" uuid NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "max_uses" integer, "use_count" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_368797218aa579a21e80d4927ff" UNIQUE ("code"), CONSTRAINT "PK_2bb111c041c01a600d6a0def77d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CHAT_INVITES_CHAT" ON "chat_invites"  ("chat_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CHAT_INVITES_CODE" ON "chat_invites"  ("code") `);
        await queryRunner.query(`CREATE TABLE "poll_votes" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "poll_id" uuid NOT NULL, "option_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b94b2749fdb5f5dd3836b8f907a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_POLL_VOTES_UNIQUE" ON "poll_votes"  ("poll_id", "option_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "poll_options" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "poll_id" uuid NOT NULL, "text" character varying(100) NOT NULL, "position" integer NOT NULL, CONSTRAINT "PK_f52aac4865d291e3658dedf9083" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_POLL_OPTIONS_POLL" ON "poll_options"  ("poll_id") `);
        await queryRunner.query(`CREATE TABLE "polls" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "message_id" uuid NOT NULL, "question" character varying(300) NOT NULL, "is_anonymous" boolean NOT NULL DEFAULT false, "is_multiple_choice" boolean NOT NULL DEFAULT false, "is_closed" boolean NOT NULL DEFAULT false, "closed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_277f1e7b5cd6b8d739420cc1d87" UNIQUE ("message_id"), CONSTRAINT "REL_277f1e7b5cd6b8d739420cc1d8" UNIQUE ("message_id"), CONSTRAINT "PK_b9bbb8fc7b142553c518ddffbb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_receipts_status_enum" AS ENUM('sent', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "message_receipts" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "message_id" uuid NOT NULL, "chat_id" uuid NOT NULL, "user_id" uuid NOT NULL, "status" "public"."message_receipts_status_enum" NOT NULL DEFAULT 'sent', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b12c7163266f985edcd141d13a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_RECEIPTS_USER_CHAT" ON "message_receipts"  ("user_id", "chat_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_RECEIPTS_MESSAGE_STATUS" ON "message_receipts"  ("message_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_RECEIPTS_MESSAGE_USER" ON "message_receipts"  ("message_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "bot_commands" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "bot_id" uuid NOT NULL, "command" character varying(50) NOT NULL, "description" character varying(200) NOT NULL, CONSTRAINT "PK_89e3e935e5ee90604edae89a5bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_BOT_COMMANDS_BOT_CMD" ON "bot_commands"  ("bot_id", "command") `);
        await queryRunner.query(`CREATE TABLE "bots" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "owner_id" uuid NOT NULL, "user_id" uuid NOT NULL, "username" character varying(50) NOT NULL, "display_name" character varying(100) NOT NULL, "description" text, "avatar_id" uuid, "token" character varying(256) NOT NULL, "webhook_url" character varying(500), "webhook_secret" character varying(100), "webhook_events" jsonb NOT NULL DEFAULT '[]', "webhook_failure_count" integer NOT NULL DEFAULT '0', "webhook_disabled_at" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_817e7b320b77555db2455d93971" UNIQUE ("username"), CONSTRAINT "UQ_db8a984f7b412bca2f520cf82f9" UNIQUE ("token"), CONSTRAINT "REL_5da286413177d0a20e7f1a4731" UNIQUE ("user_id"), CONSTRAINT "PK_8b1b0180229dec2cbfdf5e776e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_BOTS_USER" ON "bots"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOTS_OWNER" ON "bots"  ("owner_id") `);
        await queryRunner.query(`CREATE TABLE "webhook_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "bot_id" uuid NOT NULL, "delivery_id" uuid, "event_type" character varying(50) NOT NULL, "payload" jsonb, "status_code" integer, "success" boolean NOT NULL DEFAULT false, "error_message" text, "attempts" integer NOT NULL DEFAULT '1', "duration_ms" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c41f6cdf59cdfe3704807650896" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_WEBHOOK_LOGS_CREATED" ON "webhook_logs"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_WEBHOOK_LOGS_BOT_CREATED" ON "webhook_logs"  ("bot_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."calls_type_enum" AS ENUM('voice', 'video')`);
        await queryRunner.query(`CREATE TYPE "public"."calls_status_enum" AS ENUM('ringing', 'active', 'ended', 'missed', 'declined')`);
        await queryRunner.query(`CREATE TABLE "calls" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "caller_id" uuid NOT NULL, "callee_id" uuid NOT NULL, "chat_id" uuid, "type" "public"."calls_type_enum" NOT NULL DEFAULT 'voice', "status" "public"."calls_status_enum" NOT NULL DEFAULT 'ringing', "ringing_timeout_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "ended_at" TIMESTAMP WITH TIME ZONE, "duration" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9171d91f8dd1a649659f1b6a20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CALLS_RINGING_TIMEOUT" ON "calls"  ("ringing_timeout_at") WHERE status = 'ringing'`);
        await queryRunner.query(`CREATE INDEX "IDX_CALLS_STATUS" ON "calls"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_CALLS_CHAT" ON "calls"  ("chat_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_CALLS_CALLEE" ON "calls"  ("callee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_CALLS_CALLER" ON "calls"  ("caller_id") `);
        await queryRunner.query(`CREATE TYPE "public"."device_tokens_platform_enum" AS ENUM('ios', 'android', 'web')`);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "session_id" uuid NOT NULL, "token" character varying(512) NOT NULL, "platform" "public"."device_tokens_platform_enum" NOT NULL, "device_name" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_977e24c520c49436d08e5eeea8a" UNIQUE ("token"), CONSTRAINT "PK_84700be257607cfb1f9dc2e52c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_DEVICE_TOKENS_TOKEN" ON "device_tokens"  ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_DEVICE_TOKENS_SESSION" ON "device_tokens"  ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DEVICE_TOKENS_USER" ON "device_tokens"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "notification_settings" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "mute_all" boolean NOT NULL DEFAULT false, "sound_enabled" boolean NOT NULL DEFAULT true, "show_preview" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_91a7ffebe8b406c4470845d4781" UNIQUE ("user_id"), CONSTRAINT "REL_91a7ffebe8b406c4470845d478" UNIQUE ("user_id"), CONSTRAINT "PK_d131abd7996c475ef768d4559ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_NOTIFICATION_SETTINGS_USER" ON "notification_settings"  ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."sync_logs_entity_type_enum" AS ENUM('message', 'chat', 'chat_member', 'contact', 'profile', 'message_pin', 'poll', 'chat_pin', 'chat_folder', 'chat_folder_item', 'chat_mute')`);
        await queryRunner.query(`CREATE TYPE "public"."sync_logs_action_enum" AS ENUM('create', 'update', 'delete')`);
        await queryRunner.query(`CREATE TABLE "sync_logs" ("version" BIGSERIAL NOT NULL, "entity_type" "public"."sync_logs_entity_type_enum" NOT NULL, "entity_id" character varying(255) NOT NULL, "entity_key" character varying(255) NOT NULL, "action" "public"."sync_logs_action_enum" NOT NULL, "user_id" uuid, "scope_id" uuid, "payload" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a6e9e1739ed6a591efae32ec93d" PRIMARY KEY ("version"))`);
        await queryRunner.query(`CREATE INDEX "IDX_SYNC_CREATED_AT" ON "sync_logs"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_SYNC_USER_VERSION" ON "sync_logs"  ("user_id", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_SYNC_SCOPE_VERSION" ON "sync_logs"  ("scope_id", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_SYNC_VERSION" ON "sync_logs"  ("version") `);
        await queryRunner.query(`CREATE INDEX "IDX_SYNC_ENTITY_KEY_VERSION" ON "sync_logs"  ("entity_key", "version") `);
        await queryRunner.query(`CREATE TABLE "sync_state" ("key" character varying(50) NOT NULL, "value" bigint NOT NULL DEFAULT '0', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c1d9733c37275e3d785eb375ec2" PRIMARY KEY ("key"))`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_af0a71ac1879b584f255c49c99a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_5c670e5e9eaaf136e7c32c67422" FOREIGN KEY ("contact_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "FK_bf65c3db8657cef6197b68b8c88" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "FK_8b66fb69a696854d5ff08ae6e2d" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_deletions" ADD CONSTRAINT "FK_a5888bcf73fe822a32e79cd8658" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_deletions" ADD CONSTRAINT "FK_0f8839f89996c03e6d7dada6034" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_mentions" ADD CONSTRAINT "FK_704c2dc52c37d26393dae070253" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_mentions" ADD CONSTRAINT "FK_2ce356b13332ca02bfe96ae1e3d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_b6d3eda2f99b64016d6a4cf112f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7540635fef1922f0b156b9ef74f" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_54e66104dd534ed1c191e44096f" FOREIGN KEY ("reply_to_id") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_ac6b12ef0b3f9ac9d522bd0d6e2" FOREIGN KEY ("forwarded_from_id") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_12a57398d7091ce9cb83efa6005" FOREIGN KEY ("pinned_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_folders" ADD CONSTRAINT "FK_ed88dc897c85d2638e42e3875db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_members" ADD CONSTRAINT "FK_29ffb4b6edf59a7862129765339" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_members" ADD CONSTRAINT "FK_9dc61e92eed1dc151c2b2ef01a0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_members" ADD CONSTRAINT "FK_44c10f32515283abb4de24d769e" FOREIGN KEY ("folder_id") REFERENCES "chat_folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_77b7167d8a544b3f66410654778" FOREIGN KEY ("avatar_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_858cd2fadae391d81abebec30b3" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_07b7d9dde84f3d2f0403de3bf09" FOREIGN KEY ("last_message_id") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_0ac6630ca824432ec6cdb292f8b" FOREIGN KEY ("last_message_sender_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_bans" ADD CONSTRAINT "FK_7800786792a758a74037062dad7" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_bans" ADD CONSTRAINT "FK_7846dd5efb900ac9a682a1433e4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_bans" ADD CONSTRAINT "FK_1cf875b8f93aed10359a3bf50d9" FOREIGN KEY ("banned_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_invites" ADD CONSTRAINT "FK_556e214ccbf0b61e1c6ebcb9891" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_invites" ADD CONSTRAINT "FK_ad5dc7a33a9c77ec87160a850e2" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_votes" ADD CONSTRAINT "FK_ba03ab00c027c6499e7ddc73404" FOREIGN KEY ("poll_id") REFERENCES "polls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_votes" ADD CONSTRAINT "FK_433367a9fe86d90e66637310b65" FOREIGN KEY ("option_id") REFERENCES "poll_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_votes" ADD CONSTRAINT "FK_ad381571393d520e921beaf1fee" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_options" ADD CONSTRAINT "FK_c00cc693afceae746fa82c0a558" FOREIGN KEY ("poll_id") REFERENCES "polls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "polls" ADD CONSTRAINT "FK_277f1e7b5cd6b8d739420cc1d87" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_receipts" ADD CONSTRAINT "FK_781b10a45182ec12ba07780edc6" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_receipts" ADD CONSTRAINT "FK_935514fcba2f588fd9ac9fb51a1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bot_commands" ADD CONSTRAINT "FK_aedbc0b3c32cfefe295c385c823" FOREIGN KEY ("bot_id") REFERENCES "bots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "FK_ca87f8143d24a5772b02520df7b" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "FK_5da286413177d0a20e7f1a4731f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bots" ADD CONSTRAINT "FK_42c74ee615231353cb21bbea23b" FOREIGN KEY ("avatar_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_logs" ADD CONSTRAINT "FK_949aca03c30c83ece3f22f2fd41" FOREIGN KEY ("bot_id") REFERENCES "bots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_8d8b052cf7b6c41b6081c28e3f7" FOREIGN KEY ("caller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_fbb74a6e36357bfec4f668b18ae" FOREIGN KEY ("callee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_a2c3994103a6f9ba349ba42439e" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD CONSTRAINT "FK_17e1f528b993c6d55def4cf5bea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD CONSTRAINT "FK_bdd841789147ae9bf2f8d6869a5" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "FK_91a7ffebe8b406c4470845d4781" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "FK_91a7ffebe8b406c4470845d4781"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP CONSTRAINT "FK_bdd841789147ae9bf2f8d6869a5"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP CONSTRAINT "FK_17e1f528b993c6d55def4cf5bea"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_a2c3994103a6f9ba349ba42439e"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_fbb74a6e36357bfec4f668b18ae"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_8d8b052cf7b6c41b6081c28e3f7"`);
        await queryRunner.query(`ALTER TABLE "webhook_logs" DROP CONSTRAINT "FK_949aca03c30c83ece3f22f2fd41"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "FK_42c74ee615231353cb21bbea23b"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "FK_5da286413177d0a20e7f1a4731f"`);
        await queryRunner.query(`ALTER TABLE "bots" DROP CONSTRAINT "FK_ca87f8143d24a5772b02520df7b"`);
        await queryRunner.query(`ALTER TABLE "bot_commands" DROP CONSTRAINT "FK_aedbc0b3c32cfefe295c385c823"`);
        await queryRunner.query(`ALTER TABLE "message_receipts" DROP CONSTRAINT "FK_935514fcba2f588fd9ac9fb51a1"`);
        await queryRunner.query(`ALTER TABLE "message_receipts" DROP CONSTRAINT "FK_781b10a45182ec12ba07780edc6"`);
        await queryRunner.query(`ALTER TABLE "polls" DROP CONSTRAINT "FK_277f1e7b5cd6b8d739420cc1d87"`);
        await queryRunner.query(`ALTER TABLE "poll_options" DROP CONSTRAINT "FK_c00cc693afceae746fa82c0a558"`);
        await queryRunner.query(`ALTER TABLE "poll_votes" DROP CONSTRAINT "FK_ad381571393d520e921beaf1fee"`);
        await queryRunner.query(`ALTER TABLE "poll_votes" DROP CONSTRAINT "FK_433367a9fe86d90e66637310b65"`);
        await queryRunner.query(`ALTER TABLE "poll_votes" DROP CONSTRAINT "FK_ba03ab00c027c6499e7ddc73404"`);
        await queryRunner.query(`ALTER TABLE "chat_invites" DROP CONSTRAINT "FK_ad5dc7a33a9c77ec87160a850e2"`);
        await queryRunner.query(`ALTER TABLE "chat_invites" DROP CONSTRAINT "FK_556e214ccbf0b61e1c6ebcb9891"`);
        await queryRunner.query(`ALTER TABLE "chat_bans" DROP CONSTRAINT "FK_1cf875b8f93aed10359a3bf50d9"`);
        await queryRunner.query(`ALTER TABLE "chat_bans" DROP CONSTRAINT "FK_7846dd5efb900ac9a682a1433e4"`);
        await queryRunner.query(`ALTER TABLE "chat_bans" DROP CONSTRAINT "FK_7800786792a758a74037062dad7"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_0ac6630ca824432ec6cdb292f8b"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_07b7d9dde84f3d2f0403de3bf09"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_858cd2fadae391d81abebec30b3"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_77b7167d8a544b3f66410654778"`);
        await queryRunner.query(`ALTER TABLE "chat_members" DROP CONSTRAINT "FK_44c10f32515283abb4de24d769e"`);
        await queryRunner.query(`ALTER TABLE "chat_members" DROP CONSTRAINT "FK_9dc61e92eed1dc151c2b2ef01a0"`);
        await queryRunner.query(`ALTER TABLE "chat_members" DROP CONSTRAINT "FK_29ffb4b6edf59a7862129765339"`);
        await queryRunner.query(`ALTER TABLE "chat_folders" DROP CONSTRAINT "FK_ed88dc897c85d2638e42e3875db"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_12a57398d7091ce9cb83efa6005"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_ac6b12ef0b3f9ac9d522bd0d6e2"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_54e66104dd534ed1c191e44096f"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7540635fef1922f0b156b9ef74f"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_b6d3eda2f99b64016d6a4cf112f"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0"`);
        await queryRunner.query(`ALTER TABLE "message_mentions" DROP CONSTRAINT "FK_2ce356b13332ca02bfe96ae1e3d"`);
        await queryRunner.query(`ALTER TABLE "message_mentions" DROP CONSTRAINT "FK_704c2dc52c37d26393dae070253"`);
        await queryRunner.query(`ALTER TABLE "message_deletions" DROP CONSTRAINT "FK_0f8839f89996c03e6d7dada6034"`);
        await queryRunner.query(`ALTER TABLE "message_deletions" DROP CONSTRAINT "FK_a5888bcf73fe822a32e79cd8658"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "FK_8b66fb69a696854d5ff08ae6e2d"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "FK_bf65c3db8657cef6197b68b8c88"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_5c670e5e9eaaf136e7c32c67422"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_af0a71ac1879b584f255c49c99a"`);
        await queryRunner.query(`DROP TABLE "sync_state"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SYNC_ENTITY_KEY_VERSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SYNC_VERSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SYNC_SCOPE_VERSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SYNC_USER_VERSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SYNC_CREATED_AT"`);
        await queryRunner.query(`DROP TABLE "sync_logs"`);
        await queryRunner.query(`DROP TYPE "public"."sync_logs_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sync_logs_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATION_SETTINGS_USER"`);
        await queryRunner.query(`DROP TABLE "notification_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DEVICE_TOKENS_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DEVICE_TOKENS_SESSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DEVICE_TOKENS_TOKEN"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."device_tokens_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CALLS_CALLER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CALLS_CALLEE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CALLS_CHAT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CALLS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CALLS_RINGING_TIMEOUT"`);
        await queryRunner.query(`DROP TABLE "calls"`);
        await queryRunner.query(`DROP TYPE "public"."calls_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."calls_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WEBHOOK_LOGS_BOT_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WEBHOOK_LOGS_CREATED"`);
        await queryRunner.query(`DROP TABLE "webhook_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOTS_OWNER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOTS_USER"`);
        await queryRunner.query(`DROP TABLE "bots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOT_COMMANDS_BOT_CMD"`);
        await queryRunner.query(`DROP TABLE "bot_commands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RECEIPTS_MESSAGE_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RECEIPTS_MESSAGE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RECEIPTS_USER_CHAT"`);
        await queryRunner.query(`DROP TABLE "message_receipts"`);
        await queryRunner.query(`DROP TYPE "public"."message_receipts_status_enum"`);
        await queryRunner.query(`DROP TABLE "polls"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_POLL_OPTIONS_POLL"`);
        await queryRunner.query(`DROP TABLE "poll_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_POLL_VOTES_UNIQUE"`);
        await queryRunner.query(`DROP TABLE "poll_votes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_INVITES_CODE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_INVITES_CHAT"`);
        await queryRunner.query(`DROP TABLE "chat_invites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_BANS_CHAT_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_BANS_USER"`);
        await queryRunner.query(`DROP TABLE "chat_bans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHATS_LAST_MESSAGE_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHATS_USERNAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHATS_DIRECT_KEY"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TYPE "public"."chats_last_message_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chats_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_MEMBERS_CHAT_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_MEMBERS_USER"`);
        await queryRunner.query(`DROP TABLE "chat_members"`);
        await queryRunner.query(`DROP TYPE "public"."chat_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_FOLDERS_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CHAT_FOLDERS_USER_NAME"`);
        await queryRunner.query(`DROP TABLE "chat_folders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_CHAT_CREATED_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_SENDER"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_REACTIONS_MESSAGE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_REACTIONS_MESSAGE_USER"`);
        await queryRunner.query(`DROP TABLE "message_reactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MENTIONS_MESSAGE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MENTIONS_USER"`);
        await queryRunner.query(`DROP TABLE "message_mentions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGE_DELETIONS_MESSAGE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGE_DELETIONS_USER_MESSAGE"`);
        await queryRunner.query(`DROP TABLE "message_deletions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MSG_ATTACHMENTS_MESSAGE"`);
        await queryRunner.query(`DROP TABLE "message_attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CONTACTS_USER_CONTACT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CONTACTS_CONTACT_USER"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP TYPE "public"."contacts_status_enum"`);
    }

}
