[Interface]
PrivateKey = kEfId5rusvrGfpbt9Buf5YOUOjF6NMr/tdBfj8rDq0I=
Address = 10.0.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = 91QeMPZdiZNtpXXk9no3jHpqKB7lykpZmAUvc5EBJEM=
AllowedIPs = 10.0.0.2/32

[Peer]
PublicKey = admmlUCQ07tNZktpLawP81P1PZ8kne7M4TQmVDV3dzg=
AllowedIPs = 10.0.0.4/32

[Peer]
PublicKey = d7sFBx0Es7QTI69jiD98+7jnrK0gAZtlMC+CeRIwry0=
AllowedIPs = 10.0.0.3/32
