[Interface]
PrivateKey = QGJi1YvjgjCT3KJTL2Zfwm1dFj8se5Pb5IXgSq7T3kw=
Address = 10.0.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Name: Peer 1
# ID: d770456e-1473-4f39-b32b-4391be21a886
# UserID: 61f3ab53-f2b5-4fc2-90d7-aba1c29417ba
[Peer]
PublicKey = wGWEGL5ZrC2LW45xpylzpYuABGCunR5QIONDNP8TNHA=
AllowedIPs = 10.0.0.2/32
PersistentKeepalive = 25
